### ISSUE TITLE
Dates too big on mobile 

### ISSUE THREAD

**Issue by colinbate** [one-aalam/astro-ink#1]
This may be slightly subjective but the dates on the homepage are too big. They take up a lot of space from the titles causing a lot of wrapping.

**Comment by one-aalam** [comment]
Sure @colinbate. Yeah, the dates aren't adjusted much to achieve the typographic rhythm, but as a result they're occupying like ~25% of the visible width. I'll still play around and see If I can deal with this, in a much better way. 

Thank you for bringing it to my notice.

**Comment by colinbate** [comment]
Sorry, I left out the most important part of my message: "on mobile".

**Comment by colinbate** [comment]
![image](https://user-images.githubusercontent.com/1060912/132106940-9b2dea0f-8c4b-4450-a145-f28f005a7038.jpeg)

I'm sure it's less of an issue on desktop.

**Comment by one-aalam** [comment]
Np 👍 You didn't left it out. You mentioned "mobile" in the title :-) 

I pushed a small change yesterday 01ed559ffe179dca5ce57e5a9333eb551e74adaa. Not an overhaul, but it should reduce the space occupied by the date block.

<img width="519" alt="astro-ink" src="https://user-images.githubusercontent.com/532906/132124374-4bf55500-952e-4db1-978e-5e0884effdf9.png">

**Comment by colinbate** [comment]
That looks much more natural.

**Comment by one-aalam** [comment]
Closing the issue. Thank you!
