### ISSUE TITLE
Using outdated version of Astro

### ISSUE THREAD

**Issue by sarah11918** [one-aalam/astro-ink#10]
Hi there!

As you might know, Astro has recently launched v1.0.0 beta which has a lot of breaking changes from the version your theme is currently using.

Since we do link to your theme from https://astro.build/themes, would you consider adding a note to your README to let users know that the theme is running an older version of Astro and is not (yet?) compatible with Astro v1.0? We would still like to showcase and promote your work, but we also don't want to cause confusion or problems for people new to Astro.

Of course, if you're planning to upgrade this theme to Astro v1.0, that works too!  :smile: 

Thanks very much, and if you have any questions, you can reach out to me here or on the [Astro Discord](http://astro.build/chat)!

**Comment by one-aalam** [comment]
Changes incorporated by PR #11
