### ISSUE TITLE
Can we add support to math input in blog posts. Using rehype-katex preferably.

### ISSUE THREAD

**Issue by bimalgaudel** [one-aalam/astro-ink#13]

**Comment by one-aalam** [comment]
Hey @bimalgaudel, my intent with this template was to limit it to generic(and minimal) enough functionalities common to most of the blogs, and let the users decide/extend as per their liking in the clone/forks. I don't see `rehype-katex` as a common blog need. Please let me know if you see there's anything else from _blog essentials_ perspective you find missing in the template, and I'd put it in my backlog for `ink`.
