### ISSUE TITLE
Background is only set for main

### ISSUE THREAD

**Issue by palmiak** [one-aalam/astro-ink#2]
Because the background color is only set for main it can cause something like this:
![image](https://user-images.githubusercontent.com/2342458/132691284-6cc8779b-c057-45a8-84aa-45a5c8dc69ca.png)

To fix this I would move setting of the backgound color to body or by adding `min-height: 100vh;` to body.

**Comment by one-aalam** [comment]
The issue is resolved now. Thank you for bringing it to my notice.

**Comment by dmytro-lubenets-ssg** [comment]
@one-aalam I'm currently experiencing the same issue in Firefox. The tab was opened today.

**Comment by one-aalam** [comment]
Let me validate with Firefox. 

Thanks @dmytro-lubenets-ssg for bringing it to my notice.
