### ISSUE TITLE
Image doesn't get passed on to `og:image`

### ISSUE THREAD

**Issue by viveksnh** [one-aalam/astro-ink#26]
It looks like [in this line](https://github.com/one-aalam/astro-ink/blob/897707da97c98535ec615f6e0f7d686f095905d3/src/components/BaseHead.astro#L10) the image is not getting passed on as a variable. 

This results in the `og:image` to never get populated.

However, `post title` and `post description` are successfully getting populated.

I am new to astro so it may be something I am doing wrong. But I have tried to simply use the master from this repo and I do not see any `og:image` tags in the rendered html. Would love some help on making this work!

**Comment by one-aalam** [comment]
Hey, @viveksnh This issue is fixed now.

Thank you for your patience.
