### ISSUE TITLE
Nav links and tags are overflowing on mobile

### ISSUE THREAD

**Issue by bLaCkwEw** [one-aalam/astro-ink#3]
When on mobile, navigation links and tags are overflowing to the right. 

![Screenshot_20211002-213946_Firefox](https://user-images.githubusercontent.com/35146970/135728277-0c8cc7c0-8c20-449e-a9ce-be6043421a71.jpg)

**Comment by one-aalam** [comment]
Thanks for pointing this out @bLaCkwEw. I'll have a look.
