### ISSUE TITLE
Issues with fresh install - TweetEmbed

### ISSUE THREAD

**Issue by alejandronanez** [one-aalam/astro-ink#37]
Hey @one-aalam 👋 Thank you for creating this project!

I'm new to Astro, so please take this with a grain of salt. I just cloned and installed this repo, and everything was working fine (the homepage loads fine, and the navigation works, too) until I tried to render an article. I'm seeing this error.

![CleanShot 2023-04-03 at 20 38 38@2x](https://user-images.githubusercontent.com/464978/229664516-6dbd37ff-d6d6-4f28-8456-dff3d7c7704e.png)

I'm assuming I haven't configured things properly. Again, I've been using Astro for just 10 minutes 😅. I'll keep on looking to see what could be happening here.

**Comment by alejandronanez** [comment]
huh, this seems to be happening in the demo version as well 🤔 

https://astro-ink.vercel.app/blog/introducing-astro-2

@one-aalam I'm unsure how to help, but I'm happy to; just let me know 🙌 .

I'm stepping away from this for now as I don't have enough understanding of how Astro works to make a fix in a reasonable amount of time today.

**Comment by one-aalam** [comment]
👋 Hi, @alejandronanez 

Thanks for reporting this. Let me find out the root cause and fix this!

**Comment by one-aalam** [comment]
Hi @alejandronanez You shouldn't have this issue anymore if you'll have a `.env` file at the root of your app, with the `SITE_URI` configured to something like `SITE_URI=http://localhost:3000`. There's a views counter which needs this configuration. You can find more about the feature by finding "View counter feat. Redis/Upstash Redis " on the README page.

**Comment by alejandronanez** [comment]
thanks @one-aalam! I'll take a look at this tonight! 🙏

I'm closing this in the meantime and will reopen if necessary.
