### ISSUE TITLE
'dist' directory created during build and deleted after build is completed

### ISSUE THREAD

**Issue by JaredRoss14** [one-aalam/astro-ink#43]
I cloned the repo and have no local configurations made and when running `npm run build` or `astro build` locally (or when trying to deploy to Netlify) the `dist` folder is created and then deleted once the build step completes. 

I am able to run the project locally, but this is preventing a deploy on Netlify. Any thoughts on what is the cause?

**Comment by one-aalam** [comment]
Hey @JaredRoss14 The issue with static generation in the `server` mode is fixed now with the latest (2a8ca08eccb5ccaa767dffb6b365873391f45687). Please refer https://github.com/one-aalam/astro-ink#how-to-start for the instructions on the first-time setup and `static` builds.

Please feel free to report a new issue if you discover any other issue. 

Thank you for your patience!
