### ISSUE TITLE
Tags can only use lowercase letters because of `toLowerCase`

### ISSUE THREAD

**Issue by Dilettante258** [one-aalam/astro-ink#52]
![image](https://github.com/one-aalam/astro-ink/assets/113875344/acb4fb00-20f4-4c31-954d-3a2ee169e155)
Other people's web pages have also been affected by this.
[example](https://highlandcows.com/tags/AI)
<img src="https://github.com/one-aalam/astro-ink/assets/113875344/a739c639-3ba6-4851-99e4-ec1408f2e3eb" alt="image" style="zoom:30%;" />
It can be noted that when the tag is partially capitalized, the URL will not be accurately located and will redirect to 404
Even if I made changes to `ref={'/tags/${tag}.toLowerCase'} ` in `src/pages/tags/index.Astro`, I found it still very troublesome to make the changes.
So, the simplest way to solve this problem is to delete the `.toLowerCase` from other files in the tags folder.
I don't think there's a need to worry about people having multiple tags due to capitalization issues. The author should be able to modify them themselves if they see them.

**Comment by one-aalam** [comment]
Hey @Dilettante258 Thanks for reporting this. I'll look into it.

**Comment by Dilettante258** [comment]
In addition, I also noticed several other things:
- Cannot automatically generate rss.XML, even for example websites [astro-ink.vercel.app/rss.xml](https://astro-ink.vercel.app/rss.xml)
- The search function's dependency on '/search index.json' always defaults to using the local 'search index. json' in the repository, and I think there may be some issues between them. Every time I manually run a build on the local NPM and replace the old one with a new JSON generated by the build.
- robots.txt will default to denying access to all crawler robots, I don't know if this is intentional. Meanwhile, although there is a sitemaps plugin, it is not configured to use the generated XML. Here is the result of my modifications.
  ![image](https://github.com/one-aalam/astro-ink/assets/113875344/c12cf2b9-aa57-45c3-ad22-477b7f42c46a)
- The search box will not automatically follow center.
  <img src="https://github.com/one-aalam/astro-ink/assets/113875344/af3b1463-12e3-4816-8fe2-321b64f3ba80" alt="issue" style="zoom:355%;" />

Overall, I really like your blog topic. I used to use Hexo for a long time before, but now it's changed to Astro. Because I have a requirement for the Latex formula, I have made some modifications to your topic. Thank you. This is my blog[dilettante258.cyou)[https://www.dilettante258.cyou/].

**Comment by one-aalam** [comment]
All great findings @Dilettante258 👏 . Thank you for sharing. Let me find out some time to prioritise some of the key issues here.

Meanwhile, will it be possible for you to share a fix for any/some of the issues here? Any help is greatly appreciated.

**Comment by Dilettante258** [comment]
No problem, I am a student and I am currently preparing for the final exam. However, I have a solution to some of the bugs and will submit a pull request later.
