### ISSUE TITLE
src/components/Search.svelte:18:27: error: Unexpected "\u200b"

### ISSUE THREAD

**Issue by nazrdogan** [one-aalam/astro-ink#6]
I created a project using astro-ink theme. but when I run build or dev getting this error. When I fix this error manually I m getting another error. but I will open another issue for that.
<img width="1173" alt="Screenshot 2021-12-04 at 15 21 39" src="https://user-images.githubusercontent.com/1672303/144709212-77030161-2d9f-4e1f-884c-fe665efc3631.png">

**Comment by alimosallaei19** [comment]
What worked for me was that I replaced the `function () {` line in line 18 to the modern, ES6 function declaration:

`lunr(() => {` is what my line 18 looks like, and it seems to be working!

**Comment by one-aalam** [comment]
Thanks @alimosallaei19 for the recommendation. @nazrdogan LMK if the suggested solution works for you.

I'm working on migrating the theme to Astro 0.21(Vite powered) and not noticing the issue. Hope, it will fix the issue for you too. The current version with Astro 0.19 will go to a `classic` branch.

**Comment by one-aalam** [comment]
There are other errors you'd face, once this is resolved with Astro 0.19. I recommend to take the latest.

**Comment by one-aalam** [comment]
@nazrdogan I'm marking this issue as closed. Please feel free to open an issue if you find any issues with the latest updates.
